#!/usr/bin/env python3
"""
watch.py — watcher untuk raw/sources/ → auto-ingest ke wiki/

Mode:
  queue (default, aman)  : file baru → draft di wiki/inbox/ + placeholder di wiki/index.md, nunggu `confirm`
  auto  (langsung)       : file baru → langsung bikin wiki/sources/<slug>.md + update index/log (stub, perlu `lint` / ingest full LLM setelahnya)

Pakai polling biar tanpa dependency (watchdog opsional kalau ada).
Jalan:  python scripts/watch.py --mode queue
        python scripts/watch.py --mode auto --interval 2
        python scripts/watch.py --once --dry-run  # cek tanpa nulis

Debounce: tunggu file size stabil 2 detik biar nggak ke-ingest pas masih di-copy.
State: bandingin raw/sources/*.md vs wiki/sources/*.md + wiki/index.md
"""
import argparse
import time
import re
import hashlib
from pathlib import Path
from datetime import date, datetime

VAULT = Path(__file__).resolve().parents[1]
RAW = VAULT / "raw" / "sources"
WIKI_SOURCES = VAULT / "wiki" / "sources"
WIKI_INBOX = VAULT / "wiki" / "inbox"
INDEX = VAULT / "wiki" / "index.md"
LOG = VAULT / "wiki" / "log.md"

SLUG_RE = re.compile(r"[^a-z0-9]+")

def slug_from_path(p: Path) -> str:
    # 2026-08-28-judul.md -> 2026-08-28-judul  atau  judul.md -> judul
    return p.stem

def wait_stable(p: Path, sec: float = 2.0) -> bool:
    try:
        s1 = p.stat().st_size
        time.sleep(sec)
        s2 = p.stat().st_size
        return s1 == s2 and s1 > 0
    except FileNotFoundError:
        return False

def read_raw(p: Path) -> str:
    try:
        return p.read_text(encoding="utf-8", errors="ignore")
    except Exception as e:
        return f"(gagal baca: {e})"

def frontmatter(title: str, slug: str) -> str:
    today = date.today().isoformat()
    return f"""---
title: {title}
type: source
status: active
sources: [{slug}]
updated: {today}
tags: [inbox]
---

"""

def make_wiki_source_stub(raw_path: Path) -> Path:
    slug = slug_from_path(raw_path)
    title = slug.replace("-", " ").title()
    raw_text = read_raw(raw_path)
    # ambil 2 kalimat pertama sebagai summary
    first_lines = " ".join(raw_text.splitlines()[:20])[:400]
    body = f"""# {title}

## Summary

> STUB auto-generated by watch.py — perlu ingest full LLM untuk síntesis. Raw: `raw/sources/{raw_path.name}`

Draft ringkasan 1 baris: {first_lines[:180]}...

## Details

Raw preview (400 char):

```
{raw_text[:800].strip()}
```

> Ingest full: bilang `ingest raw/sources/{raw_path.name}` biar LLM pecah jadi concepts/entities + cross-ref.

## Sources

- `raw/sources/{raw_path.name}`

## Related

- [[concepts/brainpedia]]
- [[overview]]
"""
    out = WIKI_SOURCES / f"{slug}.md"
    out.write_text(frontmatter(title, slug) + body, encoding="utf-8")
    return out

def make_inbox_draft(raw_path: Path) -> Path:
    slug = slug_from_path(raw_path)
    title = slug.replace("-", " ").title()
    today = date.today().isoformat()
    body = f"""---
title: {title} (inbox)
type: source
status: planned
sources: [{slug}]
updated: {today}
tags: [inbox]
claimed_by: [watch.py]
---

# {title} — inbox

> Draft auto dari watcher (mode queue). File raw: `raw/sources/{raw_path.name}`

Tunggu konfirmasi: `confirm ingest {raw_path.name}` atau `ingest raw/sources/{raw_path.name}` untuk proses full.

Raw preview:

```
{read_raw(raw_path)[:600].strip()}
```
"""
    out = WIKI_INBOX / f"{slug}.md"
    out.write_text(body, encoding="utf-8")
    return out

def index_has_slug(slug: str) -> bool:
    if not INDEX.exists():
        return False
    txt = INDEX.read_text(encoding="utf-8", errors="ignore")
    return slug in txt

def log_append(slug: str, raw_name: str, mode: str, created: Path):
    today = date.today().isoformat()
    entry = f"""
## [{today}] ingest | auto ({mode}) — {raw_name}

- Raw: `raw/sources/{raw_name}`
- Created: `{created.relative_to(VAULT).as_posix()}` (stub, watcher)
- Mode: {mode}
- Notes: Auto via scripts/watch.py. Jalanin `ingest raw/sources/{raw_name}` untuk synthesis full LLM (concepts/entities/overview).
"""
    with LOG.open("a", encoding="utf-8") as f:
        f.write(entry)

def scan_once(mode: str, dry_run: bool = False) -> int:
    if not RAW.exists():
        print(f"RAW tidak ada: {RAW}")
        return 0
    if not WIKI_SOURCES.exists():
        WIKI_SOURCES.mkdir(parents=True, exist_ok=True)
    if not WIKI_INBOX.exists():
        WIKI_INBOX.mkdir(parents=True, exist_ok=True)

    raw_files = sorted(RAW.glob("*.md"))
    # skip README
    raw_files = [p for p in raw_files if p.name.lower() != "readme.md"]
    created = 0
    for p in raw_files:
        slug = slug_from_path(p)
        wiki_exists = (WIKI_SOURCES / f"{slug}.md").exists()
        inbox_exists = (WIKI_INBOX / f"{slug}.md").exists()
        if wiki_exists or inbox_exists or index_has_slug(slug):
            continue
        print(f"[watch] baru: {p.name} -> slug={slug} (mode={mode})")
        if not wait_stable(p, 1.5):
            print(f"  skip, file belum stabil: {p.name}")
            continue
        if dry_run:
            print(f"  dry-run, tidak nulis")
            created += 1
            continue
        if mode == "auto":
            out = make_wiki_source_stub(p)
        else:
            out = make_inbox_draft(p)
            # placeholder di index: tambah baris planned biar ingest paralel nggak duplikat (AGENTS.md §3.1)
            # append simple line ke section Concepts? cukup biar index_has_slug true di run berikutnya
            # kita tidak edit INDEX otomatis biar tidak race — cukup via inbox file
            pass
        log_append(slug, p.name, mode, out)
        print(f"  -> {out.relative_to(VAULT)}")
        created += 1
    if created == 0:
        print(f"[watch] tidak ada file baru ({len(raw_files)} raw, semua sudah ter-ingest)")
    return created

def main():
    ap = argparse.ArgumentParser(description="Watcher raw/sources/ -> wiki/")
    ap.add_argument("--mode", choices=["queue", "auto"], default="queue", help="queue=aman ke inbox, auto=langsung ke wiki/sources (default: queue)")
    ap.add_argument("--interval", type=float, default=5.0, help="detik polling (default 5)")
    ap.add_argument("--once", action="store_true", help="jalan sekali lalu exit")
    ap.add_argument("--dry-run", action="store_true", help="jangan nulis file")
    ap.add_argument("--watchdog", action="store_true", help="coba pakai watchdog jika terinstall (fallback polling)")
    args = ap.parse_args()

    # coba watchdog jika diminta
    if args.watchdog:
        try:
            from watchdog.observers import Observer
            from watchdog.events import FileSystemEventHandler
            print("[watch] mode watchdog (inotify) — belum full, fallback ke polling untuk ingest logic")
        except ImportError:
            print("[watch] watchdog tidak terinstall, pakai polling. install: pip install watchdog")

    if args.once:
        scan_once(args.mode, args.dry_run)
        return

    print(f"[watch] mulai — RAW={RAW} mode={args.mode} interval={args.interval}s (Ctrl+C stop)")
    print(f"       queue = draft ke wiki/inbox/ (confirm dulu), auto = stub ke wiki/sources/")
    try:
        while True:
            scan_once(args.mode, args.dry_run)
            time.sleep(args.interval)
    except KeyboardInterrupt:
        print("\n[watch] stop")

if __name__ == "__main__":
    main()
